spring:
  application:
    name: test2
#  boot:
#    admin:
#      client:
#        url: http://localhost:5203



server:
  port: 1025
  servlet:
    context-path: /demo2
#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
#    ${server.servlet.context-path}
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    metadata-map:
      startup: ${random.int}
      management:
        context-path: ${server.servlet.context-path}/actuator

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS



#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic