# server (eureka 默认端口为：8761)
server:
  port: 8761
# 服务名
spring:
  application:
    name: spring-cloud-server

eureka:
  client:
    # 是否注册到eureka（eureka本身是不需要再注册到自己的）
    register-with-eureka: false
    # 是否从eureka获取注册信息
    fetch-registry: false
    serviceUrl:
      # eureka服务器的地址（注意：地址最后面的 /eureka/ 这个是固定值）
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    #服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该服务，默认90秒
    leaseExpirationDurationInSeconds: 15
  server:
    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    evictionIntervalTimerInMs: 20000
    # 自我保护模式（缺省为打开）
    enable-self-preservation: true
    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS